# Generated by Django 6.1.1 on 2026-10-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_alter_product_options_remove_product_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialnumber',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myshop.product', verbose_name='Товар'),
        ),
    ]
