# Generated by Django 6.1.1 on 2026-10-10 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_remove_serialnumber_is_used_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'комментарий к товару', 'verbose_name_plural': 'комментарии к товарам'},
        ),
        migrations.AlterModelOptions(
            name='serialnumber',
            options={'verbose_name': 'серийный номер', 'verbose_name_plural': 'серийные номера'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='choice_2product',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступен для продажи'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myshop.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1-5)'),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serial_number', to='myshop.product', verbose_name='Товар'),
        ),
    ]
