# Generated by Django 6.1.1 on 2026-10-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('pages', models.IntegerField(verbose_name='Количество страниц')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Издательство')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, upload_to='book/covers/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='url_blog',
            field=models.URLField(blank=True, verbose_name='есть ссылка на ютуб?'),
        ),
    ]
